export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#240400",
        "on-surface-variant": "#444650",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#76321f",
        "primary-fixed-dim": "#b3c5ff",
        "outline": "#757681",
        "surface-variant": "#e1e3e4",
        "secondary": "#904d00",
        "on-primary-fixed-variant": "#2d4480",
        "inverse-surface": "#2e3132",
        "surface-container-highest": "#e1e3e4",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ca745c",
        "secondary-fixed-dim": "#ffb77d",
        "inverse-on-surface": "#f0f1f2",
        "surface": "#f8f9fa",
        "primary": "#000c2e",
        "on-surface": "#191c1d",
        "secondary-fixed": "#ffdcc3",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-container": "#ffa454",
        "on-secondary-container": "#713b00",
        "inverse-primary": "#b3c5ff",
        "on-primary": "#ffffff",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed": "#2f1500",
        "surface-tint": "#465c99",
        "tertiary-fixed": "#ffdbd1",
        "primary-container": "#001f5b",
        "surface-container-high": "#e7e8e9",
        "outline-variant": "#c5c6d1",
        "on-primary-fixed": "#00184a",
        "on-secondary-fixed-variant": "#6e3900",
        "tertiary-fixed-dim": "#ffb5a0",
        "surface-bright": "#f8f9fa",
        "tertiary-container": "#481002",
        "on-tertiary-fixed": "#3b0900",
        "primary-fixed": "#dbe1ff",
        "on-background": "#191c1d",
        "on-secondary": "#ffffff",
        "on-primary-container": "#7389ca",
        "background": "#f8f9fa",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
